version: "2"
services:
  web:
    build:
        context: .
    image: registry.cn-hangzhou.aliyuncs.com/t-tran/lucas:0.0.1
    environment:
      - CA_FILE=""
      - KEY_FILE=""
      - CERT_FILE=""
      - ENDPOINTS=""
    ports:
      - 8080
    restart: always
