version: "2"
services:
  web:
    build:
        context: .
    image: lucas:develop
    environment:
      - CA_FILE=""
      - KEY_FILE=""
      - CERT_FILE=""
      - ENDPOINTS=""
    ports:
      - 8080
    restart: always
